apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-staging
  namespace: argocd
spec:
  project: default
  source:
    helm:
      valueFiles:
      - values-staging.yaml    
    repoURL: https://github.com/kdrivas/practice_helm
    targetRevision: HEAD
    path: myChart
  destination:
    server: https://kubernetes.default.svc
    namespace: default
